# permissions for end users to edit postgresprofiles.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: postgresprofile-editor-role
rules:
- apiGroups:
  - database.fits.cloud
  resources:
  - postgresprofiles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - database.fits.cloud
  resources:
  - postgresprofiles/status
  verbs:
  - get
