# permissions for end users to view postgresprofiles.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: postgresprofile-viewer-role
rules:
- apiGroups:
  - database.fits.cloud
  resources:
  - postgresprofiles
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - database.fits.cloud
  resources:
  - postgresprofiles/status
  verbs:
  - get
