apiVersion: v1
kind: Namespace
metadata:
  name: database
---
apiVersion: database.fits.cloud/v1
kind: Postgres
metadata:
  namespace: database
  name: sample-name-a
spec:
  accessList:
    sourceRanges:
    - 1.2.3.4/24
  backup:
    s3BucketURL: ""
  numberOfInstances: 2
  partitionID: sample-partition
  projectID: projectid-a
  size:
    storageSize: 1Gi
  tenant: sample-tenant
  version: "12"