apiVersion: database.fits.cloud/v1
kind: Postgres
metadata:
  namespace: metal-extension-cloud
  name: standby-a
spec:
  accessList:
    sourceRanges:
    - 1.2.3.4/24
  maintenance:
    - "Sun:21:00-22:00"
  numberOfInstances: 1
  partitionID: sample-partition
  projectID: sample-project
  size:
    cpu: 500m
    memory: 512Mi
    storageSize: 1Gi
  tenant: sample-tenant
  version: "12"
  # connectionInfo:
  #   method: "streaming_host"
  #   isReplicationPrimary: true
  #   ip: "10.96.51.100" # manually add the current ip of the standby-b postgres cluster for local dev
  #   port: 5432
  #   secretName: "standby-b-passwords"