apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    control-plane: controller-manager
    {{- include "postgreslet.labels" . | nindent 4 }}
  name: {{ include "postgreslet.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      control-plane: controller-manager
      {{- include "postgreslet.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        control-plane: controller-manager
{{- if .Values.addRandomLabel }}
        random-label-to-force-reload: {{ randAlphaNum 12 | quote }}
{{- end }}
        {{- include "postgreslet.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "postgreslet.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /manager
          args:
            - --metrics-addr-svc-mgr=$(METRICS_ADDR_SVC_MGR)
            - --metrics-addr-ctrl-mgr=$(METRICS_ADDR_CTRL_MGR)
            - --enable-leader-election=$(ENABLE_LEADER_ELECTION)
            - --partition-id=$(PARTITION_ID)
            - --tenant=$(TENANT)
            - --load-balancer-ip=$(LOAD_BALANCER_IP)
            - --port-range-start=$(PORT_RANGE_START)
            - --port-range-size=$(PORT_RANGE_SIZE)
            - --custom-psp-name=$(CUSTOM_PSP_NAME)
          envFrom:
            - configMapRef:
                name: {{ include "postgreslet.fullname" . }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /var/run/secrets/postgreslet
              name: controlplane-kubeconfig
              readOnly: true
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      volumes:
        - name: controlplane-kubeconfig
          secret:
            items:
              - key: controlplane-kubeconfig
                path: kube/config
            secretName: {{ include "postgreslet.fullname" . }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
