apiVersion: v1
data:
  controlplane-kubeconfig: {{ b64enc .Values.controlplaneKubeconfig }}
kind: Secret
metadata:
  name: {{ include "postgreslet.fullname" . }}
{{- with .Values.podAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
{{- end }}
  labels:
    {{- include "postgreslet.labels" . | nindent 4 }}
