apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "postgreslet-support.roleName" . }}
rules:
- apiGroups:
  - "database.fits.cloud"
  resources:
  - postgres
  verbs:
  - get
  - list
  - watch
  - update
- apiGroups:
  - "database.fits.cloud"
  resources:
  - postgres/status
  verbs:
  - get
  - update
  - patch
