apiVersion: v1
items:
- apiVersion: v1
  data:
    api_port: "8080"
    aws_region: eu-central-1
    cluster_domain: cluster.local
    cluster_history_entries: "1000"
    cluster_labels: application:spilo
    cluster_name_label: cluster-name
    connection_pooler_default_cpu_limit: "1"
    connection_pooler_default_cpu_request: 500m
    connection_pooler_default_memory_limit: 100Mi
    connection_pooler_default_memory_request: 100Mi
    connection_pooler_image: registry.opensource.zalan.do/acid/pgbouncer:master-32
    crd_categories: all
    db_hosted_zone: db.example.com
    debug_logging: "true"
    default_cpu_limit: "1"
    default_cpu_request: 100m
    default_memory_limit: 500Mi
    default_memory_request: 100Mi
    docker_image: ghcr.io/zalando/spilo-16:3.2-p2
    enable_ebs_gp3_migration: "false"
    enable_finalizers: "false"
    enable_master_load_balancer: "false"
    enable_master_pooler_load_balancer: "false"
    enable_password_rotation: "false"
    enable_patroni_failsafe_mode: "false"
    enable_persistent_volume_claim_deletion: "true"
    enable_pgversion_env_var: "true"
    enable_readiness_probe: "false"
    enable_replica_load_balancer: "false"
    enable_replica_pooler_load_balancer: "false"
    enable_spilo_wal_path_compat: "true"
    enable_team_id_clustername_prefix: "false"
    enable_team_member_deprecation: "false"
    enable_teams_api: "false"
    external_traffic_policy: Cluster
    logical_backup_docker_image: registry.opensource.zalan.do/acid/logical-backup:v1.11.0
    logical_backup_job_prefix: logical-backup-
    logical_backup_provider: s3
    logical_backup_s3_bucket: my-bucket-url
    logical_backup_s3_sse: AES256
    logical_backup_schedule: 30 00 * * *
    major_version_upgrade_mode: manual
    master_dns_name_format: '{cluster}.{team}.{hostedzone}'
    patroni_api_check_interval: 1s
    patroni_api_check_timeout: 5s
    pdb_name_format: postgres-{cluster}-pdb
    persistent_volume_claim_retention_policy: when_deleted:retain,when_scaled:retain
    pod_deletion_wait_timeout: 10m
    pod_label_wait_timeout: 10m
    pod_management_policy: ordered_ready
    pod_role_label: spilo-role
    pod_service_account_name: postgres-pod
    pod_terminate_grace_period: 5m
    ready_wait_interval: 3s
    ready_wait_timeout: 30s
    repair_period: 5m
    replica_dns_name_format: '{cluster}-repl.{team}.{hostedzone}'
    replication_username: standby
    resource_check_interval: 3s
    resource_check_timeout: 10m
    resync_period: 30m
    ring_log_lines: "100"
    role_deletion_suffix: _deleted
    secret_name_template: '{username}.{cluster}.credentials'
    share_pgsocket_with_sidecars: "false"
    spilo_allow_privilege_escalation: "true"
    spilo_privileged: "false"
    storage_resize_mode: pvc
    super_username: postgres
    watched_namespace: '*'
    workers: "8"
  kind: ConfigMap
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","data":{"api_port":"8080","aws_region":"eu-central-1","cluster_domain":"cluster.local","cluster_history_entries":"1000","cluster_labels":"application:spilo","cluster_name_label":"cluster-name","connection_pooler_default_cpu_limit":"1","connection_pooler_default_cpu_request":"500m","connection_pooler_default_memory_limit":"100Mi","connection_pooler_default_memory_request":"100Mi","connection_pooler_image":"registry.opensource.zalan.do/acid/pgbouncer:master-32","crd_categories":"all","db_hosted_zone":"db.example.com","debug_logging":"true","default_cpu_limit":"1","default_cpu_request":"100m","default_memory_limit":"500Mi","default_memory_request":"100Mi","docker_image":"ghcr.io/zalando/spilo-16:3.2-p2","enable_ebs_gp3_migration":"false","enable_finalizers":"false","enable_master_load_balancer":"false","enable_master_pooler_load_balancer":"false","enable_password_rotation":"false","enable_patroni_failsafe_mode":"false","enable_persistent_volume_claim_deletion":"true","enable_pgversion_env_var":"true","enable_readiness_probe":"false","enable_replica_load_balancer":"false","enable_replica_pooler_load_balancer":"false","enable_spilo_wal_path_compat":"true","enable_team_id_clustername_prefix":"false","enable_team_member_deprecation":"false","enable_teams_api":"false","external_traffic_policy":"Cluster","logical_backup_docker_image":"registry.opensource.zalan.do/acid/logical-backup:v1.11.0","logical_backup_job_prefix":"logical-backup-","logical_backup_provider":"s3","logical_backup_s3_bucket":"my-bucket-url","logical_backup_s3_sse":"AES256","logical_backup_schedule":"30 00 * * *","major_version_upgrade_mode":"manual","master_dns_name_format":"{cluster}.{namespace}.{hostedzone}","patroni_api_check_interval":"1s","patroni_api_check_timeout":"5s","pdb_name_format":"postgres-{cluster}-pdb","persistent_volume_claim_retention_policy":"when_deleted:retain,when_scaled:retain","pod_deletion_wait_timeout":"10m","pod_label_wait_timeout":"10m","pod_management_policy":"ordered_ready","pod_role_label":"spilo-role","pod_service_account_name":"postgres-pod","pod_terminate_grace_period":"5m","ready_wait_interval":"3s","ready_wait_timeout":"30s","repair_period":"5m","replica_dns_name_format":"{cluster}-repl.{namespace}.{hostedzone}","replication_username":"standby","resource_check_interval":"3s","resource_check_timeout":"10m","resync_period":"30m","ring_log_lines":"100","role_deletion_suffix":"_deleted","secret_name_template":"{username}.{cluster}.credentials.{tprkind}.{tprgroup}","share_pgsocket_with_sidecars":"false","spilo_allow_privilege_escalation":"true","spilo_privileged":"false","storage_resize_mode":"pvc","super_username":"postgres","watched_namespace":"*","workers":"8"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"postgres-operator","namespace":"postgreslet-system"}}
    name: postgres-operator
    namespace: postgreslet-system
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"ServiceAccount","metadata":{"annotations":{},"name":"postgres-operator","namespace":"default"}}
    name: postgres-operator
    namespace: default
- apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRole
  metadata:
    creationTimestamp: "2022-04-21T13:43:26Z"
    name: postgres-operator
    resourceVersion: "218131001"
    uid: d7fff4ef-1265-47c0-af83-46b65a166293
  rules:
  - apiGroups:
    - acid.zalan.do
    resources:
    - postgresqls
    - postgresqls/status
    - operatorconfigurations
    verbs:
    - create
    - delete
    - deletecollection
    - get
    - list
    - patch
    - update
    - watch
  - apiGroups:
    - acid.zalan.do
    resources:
    - postgresteams
    verbs:
    - get
    - list
    - watch
  - apiGroups:
    - apiextensions.k8s.io
    resources:
    - customresourcedefinitions
    verbs:
    - create
    - get
    - patch
    - update
  - apiGroups:
    - ""
    resources:
    - configmaps
    verbs:
    - get
  - apiGroups:
    - ""
    resources:
    - events
    verbs:
    - create
    - get
    - list
    - patch
    - update
    - watch
  - apiGroups:
    - ""
    resources:
    - endpoints
    verbs:
    - create
    - delete
    - deletecollection
    - get
    - list
    - patch
    - update
    - watch
  - apiGroups:
    - ""
    resources:
    - secrets
    verbs:
    - create
    - delete
    - get
    - update
  - apiGroups:
    - ""
    resources:
    - nodes
    verbs:
    - get
    - list
    - watch
  - apiGroups:
    - ""
    resources:
    - persistentvolumeclaims
    verbs:
    - delete
    - get
    - list
    - patch
    - update
  - apiGroups:
    - ""
    resources:
    - persistentvolumes
    verbs:
    - get
    - list
    - update
  - apiGroups:
    - ""
    resources:
    - pods
    verbs:
    - delete
    - get
    - list
    - patch
    - update
    - watch
  - apiGroups:
    - ""
    resources:
    - pods/exec
    verbs:
    - create
  - apiGroups:
    - ""
    resources:
    - services
    verbs:
    - create
    - delete
    - get
    - patch
    - update
  - apiGroups:
    - apps
    resources:
    - statefulsets
    - deployments
    verbs:
    - create
    - delete
    - get
    - list
    - patch
  - apiGroups:
    - batch
    resources:
    - cronjobs
    verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
  - apiGroups:
    - ""
    resources:
    - namespaces
    verbs:
    - get
  - apiGroups:
    - policy
    resources:
    - poddisruptionbudgets
    verbs:
    - create
    - delete
    - get
  - apiGroups:
    - ""
    resources:
    - serviceaccounts
    verbs:
    - get
    - create
  - apiGroups:
    - rbac.authorization.k8s.io
    resources:
    - rolebindings
    verbs:
    - get
    - create
  - apiGroups:
    - extensions
    resourceNames:
    - privileged
    resources:
    - podsecuritypolicies
    verbs:
    - use
  - apiGroups:
    - extensions
    resourceNames:
    - postgreslet
    resources:
    - podsecuritypolicies
    verbs:
    - use
- apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRoleBinding
  metadata:
    creationTimestamp: "2022-04-21T13:43:26Z"
    name: postgres-operator
    resourceVersion: "219652419"
    uid: 87ef2de8-d2bc-4cd4-b731-1c6e8552a61d
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: postgres-operator
  subjects:
  - kind: ServiceAccount
    name: postgres-operator
    namespace: b621eb9948884911-7b0cbaf391824b4882e3
  - kind: ServiceAccount
    name: postgres-operator
    namespace: b621eb9948884911-a7b889385dbb4222b5e2
  - kind: ServiceAccount
    name: postgres-operator
    namespace: b621eb9948884911-2607e9a3f75e4ef4bbca
  - kind: ServiceAccount
    name: postgres-operator
    namespace: b621eb9948884911-dcc65c8dd9274a8eac17
  - kind: ServiceAccount
    name: postgres-operator
    namespace: fca160cadee74137-0ec69984d3f34136a065
  - kind: ServiceAccount
    name: postgres-operator
    namespace: b621eb9948884911-e0be2bf9f6834f1fb4e2
  - kind: ServiceAccount
    name: postgres-operator
    namespace: b621eb9948884911-cefe5ebb427542dda362
  - kind: ServiceAccount
    name: postgres-operator
    namespace: fca160cadee74137-87804903d9ce4abd8c7b
  - kind: ServiceAccount
    name: postgres-operator
    namespace: b621eb9948884911-a7b9e1839ae1466689a1
  - kind: ServiceAccount
    name: postgres-operator
    namespace: b621eb9948884911-927b39322ce54041b6d9
  - kind: ServiceAccount
    name: postgres-operator
    namespace: b621eb9948884911-5577b9b7335045588dc3
  - kind: ServiceAccount
    name: postgres-operator
    namespace: b621eb9948884911-d86cd6957c1c425db311
  - kind: ServiceAccount
    name: postgres-operator
    namespace: b621eb9948884911-3180bd2d947b40968cd7
- apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRole
  metadata:
    creationTimestamp: "2022-04-21T13:43:26Z"
    name: postgres-pod
    resourceVersion: "218131002"
    uid: f2ea05df-335e-4163-84f8-a77720bf9ed2
  rules:
  - apiGroups:
    - ""
    resources:
    - endpoints
    verbs:
    - create
    - delete
    - deletecollection
    - get
    - list
    - patch
    - update
    - watch
  - apiGroups:
    - ""
    resources:
    - pods
    verbs:
    - get
    - list
    - patch
    - update
    - watch
  - apiGroups:
    - ""
    resources:
    - services
    verbs:
    - create
  - apiGroups:
    - extensions
    resourceNames:
    - privileged
    resources:
    - podsecuritypolicies
    verbs:
    - use
  - apiGroups:
    - extensions
    resourceNames:
    - postgreslet
    resources:
    - podsecuritypolicies
    verbs:
    - use
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"application":"postgres-operator"},"name":"postgres-operator","namespace":"postgreslet-system"},"spec":{"replicas":1,"selector":{"matchLabels":{"name":"postgres-operator"}},"strategy":{"type":"Recreate"},"template":{"metadata":{"labels":{"name":"postgres-operator"}},"spec":{"containers":[{"env":[{"name":"CONFIG_MAP_NAME","value":"postgres-operator"}],"image":"registry.opensource.zalan.do/acid/postgres-operator:v1.11.0","imagePullPolicy":"IfNotPresent","name":"postgres-operator","resources":{"limits":{"cpu":"500m","memory":"500Mi"},"requests":{"cpu":"100m","memory":"250Mi"}},"securityContext":{"allowPrivilegeEscalation":false,"readOnlyRootFilesystem":true,"runAsNonRoot":true,"runAsUser":1000}}],"serviceAccountName":"postgres-operator"}}}}
    labels:
      application: postgres-operator
    name: postgres-operator
    namespace: postgreslet-system
  spec:
    replicas: 1
    selector:
      matchLabels:
        name: postgres-operator
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          name: postgres-operator
      spec:
        containers:
        - env:
          - name: CONFIG_MAP_NAME
            value: postgres-operator
          image: registry.opensource.zalan.do/acid/postgres-operator:v1.11.0
          imagePullPolicy: IfNotPresent
          name: postgres-operator
          resources:
            limits:
              cpu: 500m
              memory: 500Mi
            requests:
              cpu: 100m
              memory: 250Mi
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1000
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop:
              - ALL
        serviceAccountName: postgres-operator
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"postgres-operator","namespace":"postgreslet-system"},"spec":{"ports":[{"port":8080,"protocol":"TCP","targetPort":8080}],"selector":{"name":"postgres-operator"},"type":"ClusterIP"}}
    name: postgres-operator
    namespace: postgreslet-system
  spec:
    ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      name: postgres-operator
    type: ClusterIP
kind: List
metadata: {}
